language: python
env:
  - CIBW_BEFORE_BUILD: apt-get install unixodbc unixodbc-dev
  #- CIBW_BEFORE_ALL: apt-get install unixodbc unixodbc-dev
  #- CIBW_TEST_REQUIRES: apt-get install unixodbc unixodbc-dev
  #- CIBW_TEST_COMMAND: apt-get install unixodbc unixodbc-dev
  
matrix:
  include:
  - python: 2.7
  - python: 3.4
  - python: 3.5
  - python: 3.6
  - python: 3.6
    arch: arm64
  - python: 3.7
  - python: 3.7
    arch: arm64
  - python: 3.8
  - python: 3.8
    arch: arm64
    services:
      - docker
    env: BUILD_WHEEL=true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - unixodbc-dev
    
install:
  - python setup.py install
  - if [ "$BUILD_WHEEL" == "true" ]; then 
      pip install wheel cibuildwheel==1.5.2 ;
    fi

script:
  - true
  - if [ "$BUILD_WHEEL" == "true" ]; then 
      cibuildwheel --output-dir dist ;
    fi
